# Generated by Django 2.2.3 on 2019-07-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Код датчика или типо того', max_length=50)),
                ('moment', models.DateTimeField(db_index=True)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Код датчика или типо того', max_length=50)),
                ('moment', models.DateTimeField(db_index=True)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
    ]
