version: '3'
services:
  sensor-redis:
    image: redis:5
    restart: always
    env_file: env
    hostname: sensor-redis
    volumes:
      - ./data/sensor-redis:/data
  sensor-db:
    image: mdillon/postgis:11
    restart: always
    env_file: env
    hostname: sensor-db
    volumes:
      - ./data/sensor-db:/var/lib/postgresql/data
  sensor:
    build: sensor
    restart: always
    env_file: env
    depends_on:
      - sensor-redis
      - sensor-db
    ports:
      - "8001:8000"
  handler-redis:
    image: redis:5
    restart: always
    env_file: env
    hostname: handler-redis
    volumes:
      - ./data/handler-redis:/data
  handler-db:
    image: mdillon/postgis:11
    restart: always
    env_file: env
    hostname: handler-db
    volumes:
      - ./data/handler-db:/var/lib/postgresql/data
  handler:
    build: handler
    restart: always
    env_file: env
    depends_on:
      - handler-redis
      - handler-db
      - sensor-db
#      - sensor
    ports:
      - "8002:8000"
  react:
    build: react
    restart: always
    env_file: env
    depends_on:
      - handler
    ports:
      - "8000:8000"
