# Generated by Django 2.2.3 on 2019-07-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Код датчика или типо того', max_length=50)),
                ('moment', models.DateTimeField(db_index=True)),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'sensor_sensor1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Код датчика или типо того', max_length=50)),
                ('moment', models.DateTimeField(db_index=True)),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'sensor_sensor2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50, unique=True)),
                ('moment', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor1Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Сейчас не учитывается, но например разные версии датчиков имеют разный масштаб', max_length=50, null=True, unique=True)),
                ('value_expr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor2Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Сейчас не учитывается, но например разные версии датчиков имеют разный масштаб', max_length=50, null=True, unique=True)),
                ('value_expr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50)),
                ('source_id', models.PositiveIntegerField()),
                ('code', models.CharField(db_index=True, help_text='Код датчика или типо того', max_length=50)),
                ('moment', models.DateTimeField(db_index=True)),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'unique_together': {('sensor', 'source_id')},
            },
        ),
    ]
